return {
	'stevearc/conform.nvim',
	event = 'BufWritePre',
	opts = {
		formatters_by_ft = {
			lua = { 'stylua' },
			html = { 'oxfmt' },
			css = { 'oxfmt' },
			javascript = { 'oxfmt' },
			typescript = { 'oxfmt' },
			javascriptreact = { 'oxfmt' },
			typescriptreact = { 'oxfmt' },
			json = { 'oxfmt' },
			jsonc = { 'oxfmt' },
			yaml = { 'oxfmt' },
			toml = { 'oxfmt' },
			markdown = { 'oxfmt' },
			mdx = { 'oxfmt' },
			rust = { 'rustfmt' },
			tf = { 'terraform_fmt' },
			sql = { 'sql_formatter' },
			go = { 'gofumpt', 'goimports' },
			ocaml = { 'ocamlformat' },
			python = { 'ruff_format' },
		},
		format_on_save = {
			timeout_ms = 5000,
			lsp_fallback = false,
		},
	},
}
